### ISSUE TITLE
TypeError: Cannot read property 'UserService' of undefined

### ISSUE THREAD

**Issue by lexusdrumgold** [chad-app/chadapi#1]
**Describe the bug**
When trying to test my User Service, I get the following error:
```
TypeError: Cannot read property 'UserService' of undefined
```

**To Reproduce**
1. Open the project
2. Run `npm test`
3. See error

**Expected behavior**
The default export `Services` should be defined. When running `firebase.spec.js` I used the same export method for the Firebase module. `firebase.spec.js` runs without issue.

**Screenshots**
The screenshot below shows:
1) `src/config/feathers.config.js`: where I'm importing and destructuring the `Services` module
2) `src/services/index.js`: where I'm exporting the `Services` module from
3) the jest error in my terminal

![Screen Shot 2019-03-19 at 10 22 00 AM](https://user-images.githubusercontent.com/20430108/54614484-df7f6880-4a32-11e9-92fd-6ad9fa4aabdc.png)

**Additional context**
As I mentioned above, I used the same export method for the `Firebase` module. 

Line 9 of `src/config/index.js`:  
```
export Firebase from './firebase.config.js'
``` 

Line 2 of `tests/firebase.spec.js`:  
```
import Firebase from '../src/config/firebase.config.js'
```  

The above screenshot also shows the Firebase unit tests run without issue.

**Comment by davidagustin** [comment]
I see, it appears to be the export syntax.

**Comment by davidagustin** [comment]
module.exports = {
(so forth), UserService
}

**Comment by davidagustin** [comment]
When you export default, you have to use {Services}

**Comment by lexusdrumgold** [comment]
Closing for now, since one of the services is up (tested with Postman instead of Jest)
Will reopen / update later when I come back to testing with Jest
